spring:
  datasource:
    url: jdbc:mysql://kakaologin-server.mysql.database.azure.com:3306/kakaologin-database
    username: 'kquuaixstj'
    password: 'QykWQt6N8ssmd$x0'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000